# ********RoostGPT********

# Test generated by RoostGPT for test weather-api-spec using AI Type Claude AI and AI Model claude-3-5-sonnet-20241022
# 
# Feature file generated for /current.json_get for http method type GET 
# RoostTestHash=4bfd44e81d
# 
# 

# ********RoostGPT********
Feature: Current Weather API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Get current weather for valid locations
    Given path '/v1/current.json'
    And param key = karate.properties['key']
    And param q = '<location>'
    And param lang = '<language>'
    When method GET
    Then status 200
    And match response.location ==
      """
      {
        name: '#string',
        region: '#string', 
        country: '#string',
        lat: '#number',
        lon: '#number',
        tz_id: '#string',
        localtime_epoch: '#number',
        localtime: '#string'
      }
      """
    And match response.current ==
      """
      {
        last_updated_epoch: '#number',
        last_updated: '#string',
        temp_c: '#number',
        temp_f: '#number',
        is_day: '#number',
        condition: {
          text: '#string',
          icon: '#string',
          code: '#number'
        },
        wind_mph: '#number',
        wind_kph: '#number',
        wind_degree: '#number',
        wind_dir: '#string',
        pressure_mb: '#number',
        pressure_in: '#number',
        precip_mm: '#number',
        precip_in: '#number',
        humidity: '#number',
        cloud: '#number',
        feelslike_c: '#number',
        feelslike_f: '#number',
        vis_km: '#number',
        vis_miles: '#number',
        uv: '#number',
        gust_mph: '#number',
        gust_kph: '#number',
        air_quality: {
          co: '#number',
          no2: '#number',
          o3: '#number',
          so2: '#number',
          pm2_5: '#number',
          pm10: '#number',
          'us-epa-index': '#number',
          'gb-defra-index': '#number'
        }
      }
      """

    Examples:
      | read('current.json_get.csv') |

  Scenario: Get current weather without location parameter
    Given path '/v1/current.json'
    And param key = karate.properties['key']
    When method GET
    Then status 400
    And match response ==
      """
      {
        code: '#number',
        message: '#string'
      }
      """
    And match response.code == 1003
    And match response.message == "Parameter 'q' not provided."

  Scenario: Get current weather with invalid API key
    Given path '/v1/current.json'
    And param key = 'invalid_key'
    And param q = 'London'
    When method GET
    Then status 401
    And match response ==
      """
      {
        code: '#number',
        message: '#string'
      }
      """
    And match response.code == 2006
    And match response.message == "API key provided is invalid"

  Scenario: Get current weather for invalid location
    Given path '/v1/current.json'
    And param key = karate.properties['key']
    And param q = 'InvalidLocation123'
    When method GET
    Then status 400
    And match response ==
      """
      {
        code: '#number',
        message: '#string'
      }
      """
    And match response.code == 1006
    And match response.message == "No location found matching parameter 'q'"
