# ********RoostGPT********

# Test generated by RoostGPT for test weather-api-spec using AI Type Claude AI and AI Model claude-3-5-sonnet-20241022
# 
# Feature file generated for /forecast.json_get for http method type GET 
# RoostTestHash=462421f697
# 
# 

# ********RoostGPT********
Feature: Forecast Weather API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Get weather forecast with valid parameters
    Given path '/v1/forecast.json'
    And param key = karate.properties['key']
    And param q = '<location>'
    And param days = <days>
    When method GET
    Then status 200
    And match response.location == '#object'
    And match response.location.name == '#string'
    And match response.location.region == '#string'
    And match response.location.country == '#string'
    And match response.location.lat == '#number'
    And match response.location.lon == '#number'
    And match response.location.tz_id == '#string'
    And match response.location.localtime_epoch == '#number'
    And match response.location.localtime == '#string'
    And match response.current == '#object'
    And match response.current.last_updated_epoch == '#number'
    And match response.current.last_updated == '#string'
    And match response.current.temp_c == '#number'
    And match response.current.temp_f == '#number'
    And match response.current.is_day == '#number'
    And match response.current.condition == '#object'
    And match response.current.condition.text == '#string'
    And match response.current.condition.icon == '#string'
    And match response.current.condition.code == '#number'
    And match response.current.wind_mph == '#number'
    And match response.current.wind_kph == '#number'
    And match response.current.wind_degree == '#number'
    And match response.current.wind_dir == '#string'
    And match response.current.pressure_mb == '#number'
    And match response.current.pressure_in == '#number'
    And match response.current.precip_mm == '#number'
    And match response.current.precip_in == '#number'
    And match response.current.humidity == '#number'
    And match response.current.cloud == '#number'
    And match response.current.feelslike_c == '#number'
    And match response.current.feelslike_f == '#number'
    And match response.current.vis_km == '#number'
    And match response.current.vis_miles == '#number'
    And match response.current.uv == '#number'
    And match response.current.gust_mph == '#number'
    And match response.current.gust_kph == '#number'
    And match response.forecast == '#object'
    And match response.forecast.forecastday == '#[<days>]'
    And match each response.forecast.forecastday[*].date == '#string'
    And match each response.forecast.forecastday[*].date_epoch == '#number'
    And match each response.forecast.forecastday[*].day == '#object'
    And match each response.forecast.forecastday[*].day.maxtemp_c == '#number'
    And match each response.forecast.forecastday[*].day.maxtemp_f == '#number'
    And match each response.forecast.forecastday[*].day.mintemp_c == '#number'
    And match each response.forecast.forecastday[*].day.mintemp_f == '#number'
    And match each response.forecast.forecastday[*].day.avgtemp_c == '#number'
    And match each response.forecast.forecastday[*].day.avgtemp_f == '#number'
    And match each response.forecast.forecastday[*].day.maxwind_mph == '#number'
    And match each response.forecast.forecastday[*].day.maxwind_kph == '#number'
    And match each response.forecast.forecastday[*].day.totalprecip_mm == '#number'
    And match each response.forecast.forecastday[*].day.totalprecip_in == '#number'
    And match each response.forecast.forecastday[*].day.avgvis_km == '#number'
    And match each response.forecast.forecastday[*].day.avgvis_miles == '#number'
    And match each response.forecast.forecastday[*].day.avghumidity == '#number'
    And match each response.forecast.forecastday[*].day.daily_will_it_rain == '#number'
    And match each response.forecast.forecastday[*].day.daily_chance_of_rain == '#number'
    And match each response.forecast.forecastday[*].day.daily_will_it_snow == '#number'
    And match each response.forecast.forecastday[*].day.daily_chance_of_snow == '#number'
    And match each response.forecast.forecastday[*].day.condition == '#object'
    And match each response.forecast.forecastday[*].day.uv == '#number'
    And match each response.forecast.forecastday[*].astro == '#object'
    And match each response.forecast.forecastday[*].astro.sunrise == '#string'
    And match each response.forecast.forecastday[*].astro.sunset == '#string'
    And match each response.forecast.forecastday[*].astro.moonrise == '#string'
    And match each response.forecast.forecastday[*].astro.moonset == '#string'
    And match each response.forecast.forecastday[*].astro.moon_phase == '#string'
    And match each response.forecast.forecastday[*].astro.moon_illumination == '#string'

    Examples:
      | read('forecast.json_get.csv') |

  Scenario: Get weather forecast with invalid API key
    Given path '/v1/forecast.json'
    And param key = 'invalid_key'
    And param q = 'London'
    And param days = 3
    When method GET
    Then status 401
    And match response.code == 2006
    And match response.message == 'API key provided is invalid'

  Scenario: Get weather forecast without location parameter
    Given path '/v1/forecast.json'
    And param key = karate.properties['key']
    And param days = 3
    When method GET
    Then status 400
    And match response.code == 1003
    And match response.message == "Parameter 'q' not provided."

  Scenario: Get weather forecast with invalid location
    Given path '/v1/forecast.json'
    And param key = karate.properties['key']
    And param q = 'InvalidLocation123'
    And param days = 3
    When method GET
    Then status 400
    And match response.code == 1006
    And match response.message == "No location found matching parameter 'q'"

  Scenario Outline: Get weather forecast with optional parameters
    Given path '/v1/forecast.json'
    And param key = karate.properties['key']
    And param q = '<location>'
    And param days = <days>
    And param dt = '<date>'
    And param hour = <hour>
    And param alerts = '<alerts>'
    And param aqi = '<aqi>'
    When method GET
    Then status 200
    And match response.location == '#object'
    And match response.current == '#object'
    And match response.forecast == '#object'

    Examples:
      | read('forecast.json_get.csv') |
