# ********RoostGPT********

# Test generated by RoostGPT for test weather-api-spec using AI Type Claude AI and AI Model claude-3-5-sonnet-20241022
# 
# Feature file generated for /history.json_get for http method type GET 
# RoostTestHash=6ba88fbe10
# 
# 

# ********RoostGPT********
Feature: History Weather API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Get historical weather data with valid parameters
    Given path '/v1/history.json'
    And param key = karate.properties['key']
    And param q = '<location>'
    And param dt = '<date>'
    When method GET
    Then status 200
    And match response.location == '#object'
    And match response.location.name == '#string'
    And match response.location.region == '#string'
    And match response.location.country == '#string'
    And match response.location.lat == '#number'
    And match response.location.lon == '#number'
    And match response.location.tz_id == '#string'
    And match response.location.localtime_epoch == '#number'
    And match response.location.localtime == '#string'
    And match response.forecast == '#object'
    And match response.forecast.forecastday == '#array'
    And match each response.forecast.forecastday[*].date == '#string'
    And match each response.forecast.forecastday[*].date_epoch == '#number'
    And match each response.forecast.forecastday[*].day.maxtemp_c == '#number'
    And match each response.forecast.forecastday[*].day.maxtemp_f == '#number'
    And match each response.forecast.forecastday[*].day.mintemp_c == '#number'
    And match each response.forecast.forecastday[*].day.mintemp_f == '#number'
    And match each response.forecast.forecastday[*].day.avgtemp_c == '#number'
    And match each response.forecast.forecastday[*].day.avgtemp_f == '#number'
    And match each response.forecast.forecastday[*].day.maxwind_mph == '#number'
    And match each response.forecast.forecastday[*].day.maxwind_kph == '#number'
    And match each response.forecast.forecastday[*].day.totalprecip_mm == '#number'
    And match each response.forecast.forecastday[*].day.totalprecip_in == '#number'
    And match each response.forecast.forecastday[*].day.avgvis_km == '#number'
    And match each response.forecast.forecastday[*].day.avgvis_miles == '#number'
    And match each response.forecast.forecastday[*].day.avghumidity == '#number'
    And match each response.forecast.forecastday[*].day.daily_will_it_rain == '#number'
    And match each response.forecast.forecastday[*].day.daily_chance_of_rain == '#number'
    And match each response.forecast.forecastday[*].day.daily_will_it_snow == '#number'
    And match each response.forecast.forecastday[*].day.daily_chance_of_snow == '#number'
    And match each response.forecast.forecastday[*].day.condition.text == '#string'
    And match each response.forecast.forecastday[*].day.condition.icon == '#string'
    And match each response.forecast.forecastday[*].day.condition.code == '#number'
    And match each response.forecast.forecastday[*].day.uv == '#number'
    And match each response.forecast.forecastday[*].astro.sunrise == '#string'
    And match each response.forecast.forecastday[*].astro.sunset == '#string'
    And match each response.forecast.forecastday[*].astro.moonrise == '#string'
    And match each response.forecast.forecastday[*].astro.moonset == '#string'
    And match each response.forecast.forecastday[*].astro.moon_phase == '#string'
    And match each response.forecast.forecastday[*].astro.moon_illumination == '#string'

    Examples:
      | read('history.json_get.csv') |

  Scenario Outline: Get historical weather with optional hour parameter
    Given path '/v1/history.json'
    And param key = karate.properties['key']
    And param q = '<location>'
    And param dt = '<date>'
    And param hour = <hour>
    When method GET
    Then status 200
    And match response.forecast.forecastday[0].hour[<hour>].time_epoch == '#number'
    And match response.forecast.forecastday[0].hour[<hour>].temp_c == '#number'
    And match response.forecast.forecastday[0].hour[<hour>].temp_f == '#number'

    Examples:
      | read('history.json_get.csv') |

  Scenario: Invalid API key error
    Given path '/v1/history.json'
    And param key = 'invalid_key'
    And param q = 'London'
    And param dt = '2023-01-01'
    When method GET
    Then status 401
    And match response.code == 2006
    And match response.message == '#string'

  Scenario: Missing required parameter error
    Given path '/v1/history.json'
    And param key = karate.properties['key']
    And param dt = '2023-01-01'
    When method GET
    Then status 400
    And match response.code == 1003
    And match response.message == '#string'

  Scenario: Invalid location error
    Given path '/v1/history.json'
    And param key = karate.properties['key']
    And param q = 'InvalidLocation123'
    And param dt = '2023-01-01'
    When method GET
    Then status 400
    And match response.code == 1006
    And match response.message == '#string'

  Scenario Outline: Get historical weather with date range
    Given path '/v1/history.json'
    And param key = karate.properties['key']
    And param q = '<location>'
    And param dt = '<start_date>'
    And param end_dt = '<end_date>'
    When method GET
    Then status 200
    And match response.forecast.forecastday == '#array'
    And match response.forecast.forecastday[*].date contains ['<start_date>', '<end_date>']

    Examples:
      | read('history.json_get.csv') |
