# ********RoostGPT********

# Test generated by RoostGPT for test weather-api-spec using AI Type Claude AI and AI Model claude-3-5-sonnet-20241022
# 
# Feature file generated for /ip.json_get for http method type GET 
# RoostTestHash=5693e62dd1
# 
# 

# ********RoostGPT********
Feature: IP Lookup API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Successful IP lookup with valid IP address
    Given param key = karate.properties['ApiKeyAuth']
    And param q = '<ip_address>'
    When method GET
    Then status 200
    And match response ==
      """
      {
        ip: '#string',
        type: '#string',
        continent_code: '#string',
        continent_name: '#string', 
        country_code: '#string',
        country_name: '#string',
        is_eu: '#string',
        geoname_id: '#number',
        city: '##string',
        region: '##string',
        lat: '#number',
        lon: '#number',
        tz_id: '#string',
        localtime_epoch: '#number',
        localtime: '#string'
      }
      """
    And match response.ip == '<ip_address>'
    And match response.type == '#? _ == "ipv4" || _ == "ipv6"'
    And match response.continent_code == '#? _.length == 2'
    And match response.country_code == '#? _.length == 2'
    And match response.lat >= -90 && response.lat <= 90
    And match response.lon >= -180 && response.lon <= 180

    Examples:
      | read('ip.json_get.csv') |

  Scenario: Missing API key
    Given param q = '185.249.71.82'
    When method GET
    Then status 401
    And match response.code == 1002
    And match response.message == 'API key not provided'

  Scenario: Invalid API key
    Given param key = 'invalid_key'
    And param q = '185.249.71.82'
    When method GET
    Then status 401
    And match response.code == 2006
    And match response.message == 'API key provided is invalid'

  Scenario: Missing IP address parameter
    Given param key = karate.properties['ApiKeyAuth']
    When method GET
    Then status 400
    And match response.code == 1003
    And match response.message == 'Parameter \'q\' not provided.'

  Scenario: Invalid IP address format
    Given param key = karate.properties['ApiKeyAuth']
    And param q = 'invalid_ip'
    When method GET
    Then status 400
    And match response.code == 1006
    And match response.message == 'No location found matching parameter \'q\''

  Scenario: API key exceeded quota
    Given param key = karate.properties['ApiKeyAuth']
    And param q = '185.249.71.82'
    When method GET
    Then status 403
    And match response.code == 2007
    And match response.message == 'API key has exceeded calls per month quota.'

  Scenario: API key disabled
    Given param key = karate.properties['ApiKeyAuth']
    And param q = '185.249.71.82'
    When method GET
    Then status 403
    And match response.code == 2008
    And match response.message == 'API key has been disabled.'

  Scenario: API key lacks resource access
    Given param key = karate.properties['ApiKeyAuth']
    And param q = '185.249.71.82'
    When method GET
    Then status 403
    And match response.code == 2009
    And match response.message == 'API key does not have access to the resource. Please check pricing page for what is allowed in your API subscription plan.'
