# ********RoostGPT********

# Test generated by RoostGPT for test weather-api-spec using AI Type Claude AI and AI Model claude-3-5-sonnet-20241022
# 
# Feature file generated for /marine.json_get for http method type GET 
# RoostTestHash=fb78c63880
# 
# 

# ********RoostGPT********
Feature: Marine Weather API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Get marine weather forecast with valid parameters
    Given path '/v1/marine.json'
    And param key = karate.properties['key']
    And param q = '<latitude>,<longitude>'
    And param days = <days>
    When method GET
    Then status 200
    And match response.location ==
      """
      {
        name: '#string',
        region: '#string', 
        country: '#string',
        lat: '#number',
        lon: '#number',
        tz_id: '#string',
        localtime_epoch: '#number',
        localtime: '#string'
      }
      """
    And match each response.forecast.forecastday[*] ==
      """
      {
        date: '#string',
        date_epoch: '#number',
        day: {
          maxtemp_c: '#number',
          maxtemp_f: '#number',
          mintemp_c: '#number',
          mintemp_f: '#number',
          avgtemp_c: '#number',
          avgtemp_f: '#number',
          maxwind_mph: '#number',
          maxwind_kph: '#number',
          totalprecip_mm: '#number',
          totalprecip_in: '#number',
          avgvis_km: '#number',
          avgvis_miles: '#number',
          avghumidity: '#number',
          daily_will_it_rain: '#number',
          daily_chance_of_rain: '#number',
          daily_will_it_snow: '#number',
          daily_chance_of_snow: '#number',
          condition: {
            text: '#string',
            icon: '#string',
            code: '#number'
          },
          uv: '#number'
        },
        astro: {
          sunrise: '#string',
          sunset: '#string',
          moonrise: '#string',
          moonset: '#string',
          moon_phase: '#string',
          moon_illumination: '#string'
        },
        hour: '#array'
      }
      """
    And match each response.forecast.forecastday[*].hour[*] ==
      """
      {
        time_epoch: '#number',
        time: '#string',
        temp_c: '#number',
        temp_f: '#number',
        is_day: '#number',
        condition: {
          text: '#string',
          icon: '#string',
          code: '#number'
        },
        wind_mph: '#number',
        wind_kph: '#number',
        wind_degree: '#number',
        wind_dir: '#string',
        pressure_mb: '#number',
        pressure_in: '#number',
        precip_mm: '#number',
        precip_in: '#number',
        humidity: '#number',
        cloud: '#number',
        feelslike_c: '#number',
        feelslike_f: '#number',
        windchill_c: '#number',
        windchill_f: '#number',
        heatindex_c: '#number',
        heatindex_f: '#number',
        dewpoint_c: '#number',
        dewpoint_f: '#number',
        will_it_rain: '#number',
        chance_of_rain: '#number',
        will_it_snow: '#number',
        chance_of_snow: '#number',
        vis_km: '#number',
        vis_miles: '#number',
        gust_mph: '#number',
        gust_kph: '#number',
        sig_ht_mt: '#number',
        swell_ht_mt: '#number',
        swell_ht_ft: '#number',
        swell_dir: '#number',
        swell_dir_16_point: '#number',
        swell_period_secs: '#number',
        uv: '#number'
      }
      """

    Examples:
      | read('marine.json_get.csv') |

  Scenario Outline: Get marine weather forecast with optional parameters
    Given path '/v1/marine.json'
    And param key = karate.properties['key']
    And param q = '<latitude>,<longitude>'
    And param days = <days>
    And param dt = '<date>'
    And param hour = <hour>
    And param lang = '<lang>'
    When method GET
    Then status 200
    And match response.location.lat == '#number'
    And match response.location.lon == '#number'
    And match response.forecast.forecastday[0].date == '<date>'
    And match response.forecast.forecastday[0].hour[<hour>].time contains '<hour>'

    Examples:
      | read('marine.json_get.csv') |

  Scenario: Invalid API key
    Given path '/v1/marine.json'
    And param key = 'invalid_key'
    And param q = '40.71,-74.01'
    And param days = 1
    When method GET
    Then status 401
    And match response ==
      """
      {
        code: '#number',
        message: '#string'
      }
      """

  Scenario: Missing required parameter q
    Given path '/v1/marine.json'
    And param key = karate.properties['key']
    And param days = 1
    When method GET
    Then status 400
    And match response ==
      """
      {
        code: '#number',
        message: '#string'
      }
      """

  Scenario: Invalid location parameter
    Given path '/v1/marine.json'
    And param key = karate.properties['key']
    And param q = 'invalid_location'
    And param days = 1
    When method GET
    Then status 400
    And match response ==
      """
      {
        code: '#number',
        message: '#string'
      }
      """

  Scenario: Days parameter out of range
    Given path '/v1/marine.json'
    And param key = karate.properties['key']
    And param q = '40.71,-74.01'
    And param days = 8
    When method GET
    Then status 400
    And match response ==
      """
      {
        code: '#number',
        message: '#string'
      }
      """
