# ********RoostGPT********

# Test generated by RoostGPT for test weather-api-spec using AI Type Claude AI and AI Model claude-3-5-sonnet-20241022
# 
# Feature file generated for /search.json_get for http method type GET 
# RoostTestHash=72ffe69306
# 
# 

# ********RoostGPT********
Feature: Search/Autocomplete API

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Search locations with valid parameters
    Given path '/v1/search.json'
    And param key = karate.properties['key']
    And param q = query
    When method GET
    Then status 200
    And match response == '#[]'
    And match each response ==
      """
      {
        id: '#number',
        name: '#string',
        region: '#string', 
        country: '#string',
        lat: '#number',
        lon: '#number',
        url: '#string'
      }
      """
    And match each response.id == '#number'
    And match each response.name == '#string'
    And match each response.region == '#string'
    And match each response.country == '#string'
    And match each response.lat == '#number'
    And match each response.lon == '#number'
    And match each response.url == '#string'

    Examples:
      | read('search.json_get.csv') |

  Scenario: Search without query parameter
    Given path '/v1/search.json'
    And param key = karate.properties['key']
    When method GET
    Then status 400
    And match response ==
      """
      {
        code: '#number',
        message: '#string'
      }
      """
    And match response.code == 1003
    And match response.message == 'Parameter \'q\' not provided.'

  Scenario: Search with invalid API key
    Given path '/v1/search.json'
    And param key = 'invalid_key'
    And param q = 'London'
    When method GET
    Then status 401
    And match response ==
      """
      {
        code: '#number',
        message: '#string'
      }
      """
    And match response.code == 2006
    And match response.message == 'API key provided is invalid'

  Scenario: Search with non-existent location
    Given path '/v1/search.json'
    And param key = karate.properties['key']
    And param q = 'NonExistentLocation123'
    When method GET
    Then status 400
    And match response ==
      """
      {
        code: '#number',
        message: '#string'
      }
      """
    And match response.code == 1006
    And match response.message == 'No location found matching parameter \'q\''

  Scenario: Search with exceeded API quota
    Given path '/v1/search.json'
    And param key = karate.properties['key']
    And param q = 'London'
    When method GET
    Then status 403
    And match response ==
      """
      {
        code: '#number',
        message: '#string'
      }
      """
    And match response.code == 2007
    And match response.message == 'API key has exceeded calls per month quota.'
