# ********RoostGPT********

# Test generated by RoostGPT for test weather-api-spec using AI Type Claude AI and AI Model claude-3-5-sonnet-20241022
# 
# Feature file generated for /timezone.json_get for http method type GET 
# RoostTestHash=df6b1e5ce9
# 
# 

# ********RoostGPT********
Feature: Time Zone API

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Get timezone information for different locations
    Given path '/v1/timezone.json'
    And param key = karate.properties['key']
    And param q = location
    When method GET
    Then status 200
    And match response ==
      """
      {
          name: '#string',
          region: '#string', 
          country: '#string',
          lat: '#number',
          lon: '#number',
          tz_id: '#string',
          localtime_epoch: '#number',
          localtime: '#string'
      }
      """
    And match response.lat >= -90 && response.lat <= 90
    And match response.lon >= -180 && response.lon <= 180
    And match response.localtime_epoch > 0
    And match response.localtime matches '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}$'

    Examples:
      | read('timezone.json_get.csv') |

  Scenario: Missing required query parameter
    Given path '/v1/timezone.json'
    And param key = karate.properties['key']
    When method GET
    Then status 400
    And match response ==
      """
      {
          code: '#number',
          message: '#string'
      }
      """
    And match response.code == 1003
    And match response.message == 'Parameter \'q\' not provided.'

  Scenario: Invalid location parameter
    Given path '/v1/timezone.json'
    And param key = karate.properties['key']
    And param q = 'InvalidLocation123'
    When method GET
    Then status 400
    And match response ==
      """
      {
          code: '#number',
          message: '#string'
      }
      """
    And match response.code == 1006
    And match response.message contains 'No location found matching parameter'

  Scenario: Missing API key
    Given path '/v1/timezone.json'
    And param q = 'London'
    When method GET
    Then status 401
    And match response ==
      """
      {
          code: '#number',
          message: '#string'
      }
      """
    And match response.code == 1002
    And match response.message == 'API key not provided'

  Scenario: Invalid API key
    Given path '/v1/timezone.json'
    And param key = 'invalid_key'
    And param q = 'London'
    When method GET
    Then status 401
    And match response ==
      """
      {
          code: '#number',
          message: '#string'
      }
      """
    And match response.code == 2006
    And match response.message contains 'API key provided is invalid'
