# ********RoostGPT********

# Test generated by RoostGPT for test karate-jar-version-test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet_put for http method type PUT 
# RoostTestHash=3c023e4a7b
# 
# 

# ********RoostGPT********
Feature: Update an existing pet in the store

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Update pet with valid data
    Given path 'v2/pet'
    And request
      """
      { 
        "id": <id>, 
        "category": { "id": <categoryId>, "name": "<categoryName>" }, 
        "name": "<name>", 
        "photoUrls": <photoUrls>, 
        "tags": <tags>, 
        "status": "<status>" 
      }
      """
    When method PUT
    Then status 200
    And match response == '#object'
    And match response.id == '#number'
    And match response.category.id == '#number'
    And match response.category.name == '#string'
    And match response.name == '#string'
    And match response.photoUrls == '#[] string'
    And match response.tags == '#[] object'
    And match response.tags[*].id == '#[] number'
    And match response.tags[*].name == '#[] string'
    And match response.status == '#string'

    Examples:
      | read('pet_put.csv') |

  Scenario: Update pet with invalid ID
    Given path 'v2/pet'
    And request
      """
      { 
        "id": -1, 
        "category": { "id": 10, "name": "Dogs" }, 
        "name": "Max", 
        "photoUrls": ["http://example.com/max"], 
        "tags": [{"id": 101, "name": "tag1"}], 
        "status": "available" 
      }
      """
    When method PUT
    Then status 400
    And match response == '#object'
    And match response.message == '#string'

  Scenario: Update non-existing pet
    Given path 'v2/pet'
    And request
      """
      { 
        "id": 9999, 
        "category": { "id": 10, "name": "Dogs" }, 
        "name": "Max", 
        "photoUrls": ["http://example.com/max"], 
        "tags": [{"id": 101, "name": "tag1"}], 
        "status": "available" 
      }
      """
    When method PUT
    Then status 404
    And match response == '#object'
    And match response.message == '#string'

  Scenario: Update pet with validation exception
    Given path 'v2/pet'
    And request
      """
      { 
        "id": 1, 
        "category": { "id": 10, "name": "Dogs" }, 
        "name": "", 
        "photoUrls": [], 
        "tags": [], 
        "status": "unknown" 
      }
      """
    When method PUT
    Then status 405
    And match response == '#object'
    And match response.message == '#string'
