# ********RoostGPT********

# Test generated by RoostGPT for test karate-jar-version-test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet/{petId}_delete for http method type DELETE 
# RoostTestHash=1138243cb1
# 
# 

# ********RoostGPT********
Feature: Pet API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Delete a pet by ID
    Given path 'v2/pet/<petId>'
    And header api_key = <api_key>
    When method DELETE
    Then status <status>
    And match response == <responseSchema>

    Examples:
      | petId | api_key | status | responseSchema                          |
      | 12345 | null    |    404 | { message: '#string', type: '#string' } |
      | 67890 | 'key'   |    400 | { message: '#string', type: '#string' } |

  Scenario: Delete a pet with valid ID
    Given path 'v2/pet/12345'
    And header api_key = 'valid_key'
    When method DELETE
    Then status 200
    And match response == { message: '#string', type: '#string' }

  Scenario: Delete a pet with invalid ID
    Given path 'v2/pet/invalid'
    And header api_key = 'valid_key'
    When method DELETE
    Then status 400
    And match response == { message: '#string', type: '#string' }

  Scenario: Delete a pet that does not exist
    Given path 'v2/pet/99999'
    And header api_key = 'valid_key'
    When method DELETE
    Then status 404
    And match response == { message: '#string', type: '#string' }
