# ********RoostGPT********

# Test generated by RoostGPT for test karate-jar-version-test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet_post for http method type POST 
# RoostTestHash=33f954929c
# 
# 

# ********RoostGPT********
Feature: Pet Store API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Add a new pet to the store with valid input
    Given path 'v2/pet'
    And request
      """
      { 
        "id": <id>, 
        "category": { "id": <categoryId>, "name": "<categoryName>" }, 
        "name": "<name>", 
        "photoUrls": <photoUrls>, 
        "tags": <tags>, 
        "status": "<status>" 
      }
      """
    When method POST
    Then status 200
    And match response.id == '#number'
    And match response.category.id == '#number'
    And match response.category.name == '#string'
    And match response.name == '#string'
    And match response.photoUrls == '#[] string'
    And match response.tags == '#[] object'
    And match response.tags[*].id == '#[] number'
    And match response.tags[*].name == '#[] string'
    And match response.status == '#string'

    Examples:
      | read('pet_post.csv') |

  Scenario: Add a new pet with invalid input
    Given path 'v2/pet'
    And request
      """
      { 
        "name": "", 
        "photoUrls": [] 
      }
      """
    When method POST
    Then status 405
    And match response == { "description": '#string' }
