# ********RoostGPT********

# Test generated by RoostGPT for test karate-jar-version-test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet/findByTags_get for http method type GET 
# RoostTestHash=9124f669d9
# 
# 

# ********RoostGPT********
Feature: Test the /v2/pet/findByTags API endpoint

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Find pets by tags with valid input
    Given path 'v2', 'pet', 'findByTags'
    And param tags = <tags>
    When method GET
    Then status 200
    And match response == '#[]'
    And match each response == '#object'
    And match each response.id == '#number'
    And match each response.category == '#? _ == null || (_.id == #number && _.name == #string)'
    And match each response.name == '#string'
    And match each response.photoUrls == '#[]'
    And match each response.photoUrls[*] == '#string'
    And match each response.tags == '#[]'
    And match each response.tags[*].id == '#number'
    And match each response.tags[*].name == '#string'
    And match each response.status == '#string'
    And match each response.status contains ['available', 'pending', 'sold']

    Examples:
      | read('pet_findByTags_get.csv') |

  Scenario: Find pets by tags with invalid input
    Given path 'v2', 'pet', 'findByTags'
    And param tags = ['invalidTag']
    When method GET
    Then status 400
    And match response == null
