# ********RoostGPT********

# Test generated by RoostGPT for test karate-jar-version-test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet/findByStatus_get for http method type GET 
# RoostTestHash=44cafec54d
# 
# 

# ********RoostGPT********
Feature: Test Find Pets by Status API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Find pets by valid status
    Given path 'v2/pet/findByStatus'
    And param status = <status>
    When method GET
    Then status 200
    And match response == '#[]'
    And match each response == '#object'
    And match each response.id == '#number'
    And match each response.name == '#string'
    And match each response.photoUrls == '#[]'
    And match each response.photoUrls[*] == '#string'
    And match each response.category == '#? _ == null || (_.id == #number && _.name == #string)'
    And match each response.tags == '#[]'
    And match each response.tags[*].id == '#number'
    And match each response.tags[*].name == '#string'
    And match each response.status == '#string'

    Examples:
      | read('pet_findByStatus_get.csv') |

  Scenario: Find pets by invalid status
    Given path 'v2/pet/findByStatus'
    And param status = 'invalid'
    When method GET
    Then status 400
    And match response == null
