# ********RoostGPT********

# Test generated by RoostGPT for test karate-jar-version-test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /store/order/{orderId}_delete for http method type DELETE 
# RoostTestHash=36caaf0283
# 
# 

# ********RoostGPT********
Feature: Delete Purchase Order by ID

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Delete order with valid and invalid IDs
    Given path 'v2', 'store', 'order', '<orderId>'
    When method DELETE
    Then status <statusCode>
    And match response == <responseSchema>
    And match responseHeaders['Content-Type'] contains 'application/json'

    Examples:
      | orderId | statusCode | responseSchema |
      |       1 |        200 | {}             |
      |      -1 |        400 | {}             |
      |  999999 |        404 | {}             |
