# ********RoostGPT********

# Test generated by RoostGPT for test karate-jar-version-test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /store/order_post for http method type POST 
# RoostTestHash=340dd2a1e1
# 
# 

# ********RoostGPT********
Feature: Place an order for a pet

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Place an order with valid input
    Given path 'v2/store/order'
    And request
      """
      { 
        "id": <id>, 
        "petId": <petId>, 
        "quantity": <quantity>, 
        "shipDate": "<shipDate>", 
        "status": "<status>", 
        "complete": <complete> 
      }
      """
    When method POST
    Then status 200
    And match response ==
      """
      { 
        id: '#number', 
        petId: '#number', 
        quantity: '#number', 
        shipDate: '#string', 
        status: '#string', 
        complete: '#boolean' 
      }
      """
    And match response.id == <id>
    And match response.petId == <petId>
    And match response.quantity == <quantity>
    And match response.shipDate == "<shipDate>"
    And match response.status == "<status>"
    And match response.complete == <complete>

    Examples:
      | read('store_order_post.csv') |

  Scenario: Place an order with invalid input
    Given path 'v2/store/order'
    And request
      """
      { 
        "id": "invalid", 
        "petId": "invalid", 
        "quantity": "invalid", 
        "shipDate": "invalid", 
        "status": "invalid", 
        "complete": "invalid" 
      }
      """
    When method POST
    Then status 400
