# ********RoostGPT********

# Test generated by RoostGPT for test karate-jar-version-test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /store/order/{orderId}_get for http method type GET 
# RoostTestHash=959486ed06
# 
# 

# ********RoostGPT********
Feature: Store Order API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Get Order by ID - Valid ID
    Given path 'v2/store/order/<orderId>'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.id == '#number'
    And match response.petId == '#number'
    And match response.quantity == '#number'
    And match response.shipDate == '#string'
    And match response.status == '#string'
    And match response.complete == '#boolean'
    And match response.status in ['placed', 'approved', 'delivered']

    Examples:
      | read('store_order_orderId_get.csv') |

  Scenario Outline: Get Order by ID - Invalid ID
    Given path 'v2/store/order/<orderId>'
    When method GET
    Then status 400

    Examples:
      | orderId |
      |       0 |
      |      11 |

  Scenario Outline: Get Order by ID - Order Not Found
    Given path 'v2/store/order/<orderId>'
    When method GET
    Then status 404

    Examples:
      | orderId |
      |     999 |
      |    1000 |
