# ********RoostGPT********

# Test generated by RoostGPT for test karate-jar-version-test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /store/inventory_get for http method type GET 
# RoostTestHash=a66f7079af
# 
# 

# ********RoostGPT********
Feature: Store Inventory API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { api_key: karate.properties['api_key'] }

  Scenario: Get Inventory - Successful Operation
    Given path 'v2/store/inventory'
    When method GET
    Then status 200
    And match response == '#object'
    And match response contains { '#string': '#number' }
    And match responseHeaders['Content-Type'] contains 'application/json'
