# ********RoostGPT********

# Test generated by RoostGPT for test karate-jar-version-test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /user/{username}_delete for http method type DELETE 
# RoostTestHash=5caa5e3efb
# 
# 

# ********RoostGPT********
Feature: User API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Delete User by Username
    Given path 'v2/user', '<username>'
    When method DELETE
    Then status <statusCode>
    And match response == null
    And match responseHeaders['Content-Type'] contains 'application/json'

    Examples:
      | username    | statusCode |
      | validUser   |        200 |
      | invalidUser |        404 |
      |             |        400 |
