# ********RoostGPT********

# Test generated by RoostGPT for test karate-jar-version-test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /user/{username}_get for http method type GET 
# RoostTestHash=b96457affd
# 
# 

# ********RoostGPT********
Feature: User API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Get user by username
    Given path 'v2/user/<username>'
    When method GET
    Then status <status>
    And match responseHeaders['Content-Type'] contains 'application/json'
    And match response == '#object'
    And match response.id == '#number'
    And match response.username == '#string'
    And match response.firstName == '#string'
    And match response.lastName == '#string'
    And match response.email == '#string'
    And match response.password == '#string'
    And match response.phone == '#string'
    And match response.userStatus == '#number'

    Examples:
      | username | status |
      | user1    |    200 |
      | invalid  |    400 |
      | notfound |    404 |
