# ********RoostGPT********

# Test generated by RoostGPT for test karate-jar-version-test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /user/createWithArray_post for http method type POST 
# RoostTestHash=2fceff8367
# 
# 

# ********RoostGPT********
Feature: Create Users with Array Input

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Create users with valid array input
    Given path 'v2/user/createWithArray'
    And request """<requestBody>"""
    When method POST
    Then status 200
    And match response == '#object'
    And match response.headers['Content-Type'] contains 'application/json'
    And match response.body == '#object'

    Examples:
      | read('user_createWithArray_post.csv') |

  Scenario: Create users with empty array
    Given path 'v2/user/createWithArray'
    And request """[]"""
    When method POST
    Then status 200
    And match response == '#object'
    And match response.headers['Content-Type'] contains 'application/json'
    And match response.body == '#object'

  Scenario: Create users with invalid input
    Given path 'v2/user/createWithArray'
    And request """[ { "id": "invalid", "username": 123, "firstName": true, "lastName": null, "email": "invalid", "password": 12345, "phone": false, "userStatus": "invalid" } ]"""
    When method POST
    Then status 200
    And match response == '#object'
    And match response.headers['Content-Type'] contains 'application/json'
    And match response.body == '#object'
