# ********RoostGPT********

# Test generated by RoostGPT for test karate-jar-version-test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /user/{username}_put for http method type PUT 
# RoostTestHash=ec22222bac
# 
# 

# ********RoostGPT********
Feature: Update User API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Update user with valid data
    Given path 'v2/user/<username>'
    And request
      """
      { 
        "id": <id>, 
        "username": "<newUsername>", 
        "firstName": "<firstName>", 
        "lastName": "<lastName>", 
        "email": "<email>", 
        "password": "<password>", 
        "phone": "<phone>", 
        "userStatus": <userStatus> 
      }
      """
    When method PUT
    Then status 200
    And match response == '#object'
    And match response.id == '#number'
    And match response.username == '#string'
    And match response.firstName == '#string'
    And match response.lastName == '#string'
    And match response.email == '#string'
    And match response.password == '#string'
    And match response.phone == '#string'
    And match response.userStatus == '#number'

    Examples:
      | read('user_username_put.csv') |

  Scenario Outline: Update user with invalid username
    Given path 'v2/user/<username>'
    And request
      """
      { 
        "id": <id>, 
        "username": "<newUsername>", 
        "firstName": "<firstName>", 
        "lastName": "<lastName>", 
        "email": "<email>", 
        "password": "<password>", 
        "phone": "<phone>", 
        "userStatus": <userStatus> 
      }
      """
    When method PUT
    Then status 404
    And match response == '#object'
    And match response.message == '#string'

    Examples:
      | username | id | newUsername | firstName | lastName | email            | password | phone      | userStatus |
      | invalid  |  1 | newUser1    | John      | Doe      | john@example.com | pass123  | 1234567890 |          1 |

  Scenario Outline: Update user with invalid data
    Given path 'v2/user/<username>'
    And request
      """
      { 
        "id": <id>, 
        "username": "<newUsername>", 
        "firstName": "<firstName>", 
        "lastName": "<lastName>", 
        "email": "<email>", 
        "password": "<password>", 
        "phone": "<phone>", 
        "userStatus": <userStatus> 
      }
      """
    When method PUT
    Then status 400
    And match response == '#object'
    And match response.message == '#string'

    Examples:
      | username | id | newUsername | firstName | lastName | email         | password | phone      | userStatus |
      | user1    |  1 |             | John      | Doe      | invalid-email | pass123  | 1234567890 |          1 |
