# ********RoostGPT********

# Test generated by RoostGPT for test karate-jar-version-test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /user/login_get for http method type GET 
# RoostTestHash=d905dac95c
# 
# 

# ********RoostGPT********
Feature: User Login API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Successful login with valid credentials
    Given path 'v2/user/login'
    And param username = '<username>'
    And param password = '<password>'
    When method GET
    Then status 200
    And match response == '#string'
    And match responseHeaders['X-Expires-After'] == '#string'
    And match responseHeaders['X-Rate-Limit'] == '#number'

    Examples:
      | read('user_login_get.csv') |

  Scenario Outline: Login with invalid credentials
    Given path 'v2/user/login'
    And param username = '<username>'
    And param password = '<password>'
    When method GET
    Then status 400
    And match response == '#string'

    Examples:
      | username | password |
      | invalid  | wrong    |
      | user1    | wrong    |
