# ********RoostGPT********

# Test generated by RoostGPT for test karate-jar-version-test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /user/createWithList_post for http method type POST 
# RoostTestHash=41ad79e90d
# 
# 

# ********RoostGPT********
Feature: Create Users with List Input

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Create users with valid input array
    Given path 'v2/user/createWithList'
    And request
      """
      [
        { 
          "id": <id>, 
          "username": '<username>', 
          "firstName": '<firstName>', 
          "lastName": '<lastName>', 
          "email": '<email>', 
          "password": '<password>', 
          "phone": '<phone>', 
          "userStatus": <userStatus> 
        }
      ]
      """
    When method POST
    Then status 200
    And match response == '#object'
    And match response.headers['Content-Type'] contains 'application/json'

    Examples:
      | read('user_createWithList_post.csv') |

  Scenario: Create users with empty input array
    Given path 'v2/user/createWithList'
    And request []
    When method POST
    Then status 200
    And match response == '#object'
    And match response.headers['Content-Type'] contains 'application/json'
