# ********RoostGPT********

# Test generated by RoostGPT for test karate-jar-version-test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /user/logout_get for http method type GET 
# RoostTestHash=696422fb14
# 
# 

# ********RoostGPT********
Feature: User Logout API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario: Logout user with valid session
    Given path 'v2', 'user', 'logout'
    When method GET
    Then status 200
    And match response == '#null'
    And match responseHeaders['Content-Type'] contains 'application/json'

  Scenario: Logout user with invalid session
    Given path 'v2', 'user', 'logout'
    When method GET
    Then status 401
    And match response == '#null'
    And match responseHeaders['Content-Type'] contains 'application/json'

  Scenario: Logout user without session
    Given path 'v2', 'user', 'logout'
    When method GET
    Then status 401
    And match response == '#null'
    And match responseHeaders['Content-Type'] contains 'application/json'
