# ********RoostGPT********

# Test generated by RoostGPT for test karate-jar-version-test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /user_post for http method type POST 
# RoostTestHash=d815599fc6
# 
# 

# ********RoostGPT********
Feature: User API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Create User with valid input
    Given path 'v2/user'
    And request
      """
      { 
        "id": <id>, 
        "username": '<username>', 
        "firstName": '<firstName>', 
        "lastName": '<lastName>', 
        "email": '<email>', 
        "password": '<password>', 
        "phone": '<phone>', 
        "userStatus": <userStatus> 
      }
      """
    When method POST
    Then status 200
    And match response == '#object'
    And match response.id == '#number'
    And match response.username == '#string'
    And match response.firstName == '#string'
    And match response.lastName == '#string'
    And match response.email == '#string'
    And match response.password == '#string'
    And match response.phone == '#string'
    And match response.userStatus == '#number'

    Examples:
      | read('user_post.csv') |

  Scenario: Create User with missing body
    Given path 'v2/user'
    When method POST
    Then status 400
    And match response == '#object'
    And match response.message == '#string'

  Scenario: Create User with invalid data type
    Given path 'v2/user'
    And request
      """
      { 
        "id": "invalid", 
        "username": 123, 
        "firstName": true, 
        "lastName": null, 
        "email": 456, 
        "password": false, 
        "phone": {}, 
        "userStatus": "status" 
      }
      """
    When method POST
    Then status 400
    And match response == '#object'
    And match response.message == '#string'
