# ********RoostGPT********

# Test generated by RoostGPT for test weather-api-spec using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /current.json_get for http method type GET 
# RoostTestHash=4bfd44e81d
# 
# 

# ********RoostGPT********
Feature: Realtime Weather API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * def authToken = karate.properties['key']
    * header Accept = 'application/json'

  Scenario Outline: Get current weather data with valid parameters
    Given path '/v1/current.json'
    And param key = authToken
    And param q = <q>
    And param lang = <lang>
    When method GET
    Then status 200
    And match response.location == '#object'
    And match response.location.name == '#string'
    And match response.location.region == '#string'
    And match response.location.country == '#string'
    And match response.location.lat == '#number'
    And match response.location.lon == '#number'
    And match response.location.tz_id == '#string'
    And match response.location.localtime_epoch == '#number'
    And match response.location.localtime == '#string'
    And match response.current == '#object'
    And match response.current.last_updated_epoch == '#number'
    And match response.current.last_updated == '#string'
    And match response.current.temp_c == '#number'
    And match response.current.temp_f == '#number'
    And match response.current.is_day == '#number'
    And match response.current.condition == '#object'
    And match response.current.condition.text == '#string'
    And match response.current.condition.icon == '#string'
    And match response.current.condition.code == '#number'
    And match response.current.wind_mph == '#number'
    And match response.current.wind_kph == '#number'
    And match response.current.wind_degree == '#number'
    And match response.current.wind_dir == '#string'
    And match response.current.pressure_mb == '#number'
    And match response.current.pressure_in == '#number'
    And match response.current.precip_mm == '#number'
    And match response.current.precip_in == '#number'
    And match response.current.humidity == '#number'
    And match response.current.cloud == '#number'
    And match response.current.feelslike_c == '#number'
    And match response.current.feelslike_f == '#number'
    And match response.current.vis_km == '#number'
    And match response.current.vis_miles == '#number'
    And match response.current.uv == '#number'
    And match response.current.gust_mph == '#number'
    And match response.current.gust_kph == '#number'
    And match response.current.air_quality == '##object'
    And if (response.current.air_quality) match response.current.air_quality.co == '#number'
    And if (response.current.air_quality) match response.current.air_quality.no2 == '#number'
    And if (response.current.air_quality) match response.current.air_quality.o3 == '#number'
    And if (response.current.air_quality) match response.current.air_quality.so2 == '#number'
    And if (response.current.air_quality) match response.current.air_quality.pm2_5 == '#number'
    And if (response.current.air_quality) match response.current.air_quality.pm10 == '#number'
    And if (response.current.air_quality) match response.current.air_quality['us-epa-index'] == '#number'
    And if (response.current.air_quality) match response.current.air_quality['gb-defra-index'] == '#number'

    Examples:
      | read('current.json_get.csv') |

  Scenario: Get current weather data without language parameter
    Given path '/v1/current.json'
    And param key = authToken
    And param q = 'Paris'
    When method GET
    Then status 200
    And match response.location == '#object'
    And match response.location.name == '#string'
    And match response.location.region == '#string'
    And match response.location.country == '#string'
    And match response.location.lat == '#number'
    And match response.location.lon == '#number'
    And match response.location.tz_id == '#string'
    And match response.location.localtime_epoch == '#number'
    And match response.location.localtime == '#string'
    And match response.current == '#object'
    And match response.current.last_updated_epoch == '#number'
    And match response.current.last_updated == '#string'
    And match response.current.temp_c == '#number'
    And match response.current.temp_f == '#number'
    And match response.current.is_day == '#number'
    And match response.current.condition == '#object'
    And match response.current.condition.text == '#string'
    And match response.current.condition.icon == '#string'
    And match response.current.condition.code == '#number'
    And match response.current.wind_mph == '#number'
    And match response.current.wind_kph == '#number'
    And match response.current.wind_degree == '#number'
    And match response.current.wind_dir == '#string'
    And match response.current.pressure_mb == '#number'
    And match response.current.pressure_in == '#number'
    And match response.current.precip_mm == '#number'
    And match response.current.precip_in == '#number'
    And match response.current.humidity == '#number'
    And match response.current.cloud == '#number'
    And match response.current.feelslike_c == '#number'
    And match response.current.feelslike_f == '#number'
    And match response.current.vis_km == '#number'
    And match response.current.vis_miles == '#number'
    And match response.current.uv == '#number'
    And match response.current.gust_mph == '#number'
    And match response.current.gust_kph == '#number'

  Scenario Outline: Handle 400 Bad Request errors
    Given path '/v1/current.json'
    And param key = authToken
    And param q = <q>
    When method GET
    Then assert responseStatus != 200
    And status 400
    And match response.code == '#number'
    And match response.message == '#string'

    Examples:
      | q                       |
      | ''                      |
      | 'InvalidLocationXYZ123' |

  Scenario: Handle 401 Unauthorized - Missing API key
    Given path '/v1/current.json'
    And param q = 'London'
    When method GET
    Then assert responseStatus != 200
    And status 401
    And match response.code == '#number'
    And match response.message == '#string'

  Scenario: Handle 401 Unauthorized - Invalid API key
    Given path '/v1/current.json'
    And param key = 'invalid_api_key'
    And param q = 'London'
    When method GET
    Then assert responseStatus != 200
    And status 401
    And match response.code == '#number'
    And match response.message == '#string'

  Scenario: Handle 403 Forbidden - API key quota exceeded
    Given path '/v1/current.json'
    And param key = authToken
    And param q = 'London'
    When method GET
    Then if (responseStatus == 403) match response.code == '#number'
    And if (responseStatus == 403) match response.message == '#string'
