# ********RoostGPT********

# Test generated by RoostGPT for test CrediCard-Karate using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /collection-notification_post for http method type POST 
# RoostTestHash=c6dc500cd4
# 
# 

# ********RoostGPT********
Feature: Collection Notification API

Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

Scenario: Successful collection notification
    Given path '/collection-notification'
    And header Authorization = 'Bearer ' + authToken
    And request
        """
        {
            "delinquencyStatus": "OVERDUE",
            "outstandingBalance": "1000.00",
            "additionalCharges": "50.00",
            "cardLast4": "1234"
        }
        """
    When method POST
    Then status 200
    And match response == '#string'

Scenario: Missing required fields
    Given path '/collection-notification'
    And header Authorization = 'Bearer ' + authToken
    And request
        """
        {
            "delinquencyStatus": "OVERDUE",
            "outstandingBalance": "1000.00"
        }
        """
    When method POST
    Then status 422
    # And match response contains 'Missing required fields'

Scenario Outline: Invalid card last 4 digits
    Given path '/collection-notification'
    And header Authorization = 'Bearer ' + authToken
    And request
        """
        {
            "delinquencyStatus": "OVERDUE",
            "outstandingBalance": "1000.00",
            "additionalCharges": "50.00",
            "cardLast4": "<invalidCardLast4>"
        }
        """
    When method POST
    Then status 422
    # And match response contains 'Invalid card last 4 digits'

    Examples:
        | invalidCardLast4 |
        | 123              |
        | 12345            |
        | abcd             |
