# ********RoostGPT********

# Test generated by RoostGPT for test CrediCard-Karate using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /payment-reminder_post for http method type POST 
# RoostTestHash=821572435a
# 
# 

# ********RoostGPT********
Feature: Payment Reminder API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['AUTH_TOKEN']

Scenario Outline: Payment Reminder - Successful Response
  Given path '/payment-reminder'
  And header Authorization = 'Bearer ' + authToken
  And request
    """
    {
      "currentDate": "<currentDate>",
      "paymentDueDate": "<paymentDueDate>",
      "cardLast4": "<cardLast4>"
    }
    """
  When method POST
  Then status 200
  # And match response == "<expectedResponse>"

  Examples:
    | currentDate | paymentDueDate | cardLast4 | expectedResponse                     |
    | 2023-06-01  | 2023-06-15     | 1234      | "Payment reminder sent successfully" |
    | 2023-07-10  | 2023-07-20     | 5678      | "Payment reminder sent successfully" |

Scenario: Payment Reminder - Missing Required Fields
  Given path '/payment-reminder'
  And header Authorization = 'Bearer ' + authToken
  And request
    """
    {
      "currentDate": "2023-06-01"
    }
    """
  When method POST
  Then status 422
  # And match response contains "Missing required fields"

Scenario: Payment Reminder - Invalid Card Last 4
  Given path '/payment-reminder'
  And header Authorization = 'Bearer ' + authToken
  And request
    """
    {
      "currentDate": "2023-06-01",
      "paymentDueDate": "2023-06-15",
      "cardLast4": "123"
    }
    """
  When method POST
  Then status 422
  # And match response contains "Invalid cardLast4 format"

Scenario: Payment Reminder - Invalid Date Format
  Given path '/payment-reminder'
  And header Authorization = 'Bearer ' + authToken
  And request
    """
    {
      "currentDate": "2023/06/01",
      "paymentDueDate": "2023-06-15",
      "cardLast4": "1234"
    }
    """
  When method POST
  Then status 422
  # And match response contains "Invalid date format"
